"use client";
import {useEffect,useState} from "react";
import {Copy,Check,Users,Coins,Zap,Wind,LockKeyhole,Shield,Trophy,Target,LoaderCircle,Flag} from "lucide-react";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {Progress} from "@/components/ui/progress";
import {shots,deliveries,inningsEnded,type PublicRoom,type Mode,type Outcome} from "@/lib/game";
const over=(n:number)=>Math.floor(n/6)+"."+n%6;
type Props={room:PublicRoom;busy:boolean;error:string;act:(a:Record<string,unknown>)=>Promise<void>;exit:()=>void;showRules:()=>void};
export default function Match({room:r,busy,error,act,exit,showRules}:Props){
 const [selected,setSelected]=useState<string>(""),[style,setStyle]=useState<Mode|null>(null),[copied,setCopied]=useState("");
 useEffect(()=>{setSelected("");setStyle(null);},[r.round,r.phase,r.mode]);
 const innings=r.innings.at(-1),batter=innings?.batter??0,isBatting=innings?.batter===r.you,last=innings?.balls.at(-1),me=r.players[r.you],other=r.players[1-r.you],ended=!!innings&&(innings.wickets>=3||innings.balls.length>=r.overs*6),target=r.innings[0]?r.innings[0].runs+1:0;
 async function copy(value:string,label:string){try{await navigator.clipboard.writeText(value);setCopied(label);setTimeout(()=>setCopied(""),2200);}catch{setCopied("Copy manually: "+value);}}
 const runAction=(a:Record<string,unknown>)=>act({...a,round:r.round});
 const resultTitle=last?.outcome==="W"?"WICKET!":last?.outcome===6?"THAT’S A SIX!":last?.outcome===4?"FOUR. BEAUTIFUL.":last?.outcome===0?"DOT BALL.":last?.outcome+" RUN"+(last?.outcome===1?"":"S");
 const winnerName=r.winner===null?"It’s a tie.":r.players[r.winner].name+" wins!";
 function chooseCards(){
  const choices=isBatting?shots:deliveries[r.mode!];
  return <><div className="action-heading"><span className="tag">{isBatting?"AT THE CREASE":"ON THE ATTACK"}</span><span className="action-ball">BALL {Math.min((innings?.balls.length??0)+1,r.overs*6)} / {r.overs*6}</span></div><h2>{isBatting?"Pick your shot.":"Pick your delivery."}</h2><p className="subtext">{isBatting?"Read the bowler. Trust your instinct.":"Find the weakness. Make it count."} <b className="lime">{r.mode==="pace"?"Pace":"Spin"} bowling</b></p>
  {r.locked[r.you]?<div className="locked-panel"><LockKeyhole size={32}/><h3>Choice locked.</h3><p>{other?.name} is choosing. Your move stays hidden.</p></div>:<><RadioGroup value={selected} onValueChange={setSelected} className="move-grid" aria-label={isBatting?"Choose your shot":"Choose your delivery"}>{choices.map((c,i)=><label className={"move-card "+(selected===String(i)?"selected":"")} key={c.name}><RadioGroupItem className="sr-only" value={String(i)} aria-label={c.name}/><span className="move-top"><span>{String(i+1).padStart(2,"0")}</span>{selected===String(i)?<Check size={17}/>:<Target size={17}/>}</span><b>{c.name}</b><span>{c.desc}</span></label>)}</RadioGroup><button disabled={busy||selected===""} className="primary-button" onClick={()=>runAction({action:"move",move:Number(selected)})}><LockKeyhole size={17}/> {busy?"Locking choice…":isBatting?"Lock my shot":"Lock my delivery"}</button><p className="form-hint center">Choices reveal only after both players lock in.</p></>}
  {r.locked[1-r.you]&&!r.locked[r.you]&&<p className="opponent-locked"><Check size={15}/>{other?.name} has locked their choice.</p>}</>;
 }
 return <main className="lobby-main match-main"><div className="match-toolbar"><div className="page-label"><span className="small-line"/>MATCH ROOM <button className="room-code-mini" onClick={()=>copy(r.code,"code")}>{r.code} {copied==="code"?<Check size={14}/>:<Copy size={14}/>}</button></div><button className="quiet-button" onClick={exit}>Back to lobby</button></div>
 <div className="match-grid"><section className="score-column"><div className="score-stadium"><img className="stadium-image" src="/stadium.png" alt="Night cricket stadium"/><div className="stadium-shade"/><div className="score-top"><span className="tag">{r.phase==="complete"?"FULL TIME":innings?("INNINGS "+r.innings.length+" OF 2"):"PRE-MATCH"}</span><span>{r.overs} {r.overs===1?"OVER":"OVERS"} · 3 WICKETS</span></div><div className="big-score"><p>{innings?r.players[batter].name:"THE STAGE IS YOURS"}</p><div>{innings?<>{innings.runs}<span>/{innings.wickets}</span></>:<SwordsLabel/>}</div><p className="score-meta">{innings?<>{over(innings.balls.length)} <span>/ {r.overs} overs</span> · <b>{isBatting?"You are batting":"You are bowling"}</b></>:"Two players. One match. Everything to play for."}</p></div>
 {innings&&r.innings.length===2?<div className="chase-banner"><Flag size={17}/><span>TARGET <b>{target}</b> · {Math.max(0,target-innings.runs)} needed from {Math.max(0,r.overs*6-innings.balls.length)} balls</span></div>:<div className="chase-banner"><Shield size={17}/><span>{innings?"Set the score. Make them chase.":"Secret choices. Real rivalry."}</span></div>}</div>
 <div className="player-score-list">{[0,1].map(p=>{const score=r.innings.find(i=>i.batter===p);return <div className={"player-score "+(p===batter&&innings?"active":"")} key={p}><div className={"avatar "+(p===1?"guest-avatar":"")}>{r.players[p]?.name?.slice(0,1).toUpperCase()??"?"}</div><div><b>{r.players[p]?.name??"Waiting for opponent"}{p===r.you&&<span className="you-tag">YOU</span>}</b><p>{score?over(score.balls.length)+" overs":r.players[p]?"Ready for the match":"Share your room code"}</p></div><strong>{score?score.runs+"/"+score.wickets:"—"}</strong></div>;})}</div>
 {innings&&<div className="over-panel"><div className="section-label">THIS OVER<span>{over(innings.balls.length)} / {r.overs}</span></div><div className="ball-strip">{Array.from({length:6},(_,i)=>{const start=innings.balls.length?Math.floor((innings.balls.length-1)/6)*6:0;const ball=innings.balls[start+i];return <span className={"ball-chip "+(ball?ball.outcome==="W"?"wicket":Number(ball.outcome)>=4?"boundary":"played":"")} key={i}>{ball?ball.outcome:"·"}</span>;})}</div><Progress value={innings.balls.length/(r.overs*6)*100} aria-label="Innings progress" className="innings-progress"/></div>}
 <div className="tactics-tip"><Target size={20}/><div><b>Good cricket starts in the mind.</b><p>Switch up your choices. Keep your opponent guessing.</p><button className="text-button" onClick={showRules}>View shot & delivery matchups</button></div></div></section>
 <section className="action-panel" aria-live="polite">
 {error&&<p className="error-text" role="alert">{error}</p>}
 {r.phase==="waiting"&&<div className="room-wait"><div className="large-icon"><Users size={31}/></div><span className="panel-kicker">YOUR ROOM IS READY</span><h2>Bring your rival.</h2><p className="subtext">Send this code to a friend. They can join from their own device.</p><div className="big-room-code">{r.code}</div><div className="copy-actions"><button className="primary-button" onClick={()=>copy(r.code,"code")}><Copy size={17}/>{copied==="code"?"Copied!":"Copy room code"}</button><button className="secondary-button" onClick={()=>copy(window.location.origin+"/?room="+r.code,"link")}>{copied==="link"?"Link copied!":"Copy invite link"}</button></div><p className="form-hint">Room expires in 24 hours. Two players maximum.</p><div className="waiting-line"><LoaderCircle size={18} className="spin"/>Waiting for your opponent to join</div>{copied.startsWith("Copy manually:")&&<p className="form-hint">{copied}</p>}</div>}
 {r.phase==="toss"&&<div className="room-wait"><div className="coin"><Coins size={49}/></div><span className="panel-kicker">THE COIN TOSS</span><h2>{r.you===1?"Call it in the air.":"Your opponent calls."}</h2><p className="subtext">Winner decides who bats first.</p>{r.you===1?<div className="two-buttons"><button className="secondary-button" disabled={busy} onClick={()=>act({action:"toss",call:"heads"})}>Heads</button><button className="secondary-button" disabled={busy} onClick={()=>act({action:"toss",call:"tails"})}>Tails</button></div>:<p className="waiting-line"><LoaderCircle className="spin" size={18}/>{other?.name} is calling heads or tails.</p>}</div>}
 {r.phase==="choose"&&<div className="room-wait"><div className="coin landed">{r.toss?.face==="heads"?"H":"T"}</div><span className="panel-kicker">IT’S {r.toss?.face.toUpperCase()}</span><h2>{r.toss?.winner===r.you?"You won the toss.":r.players[r.toss!.winner].name+" won the toss."}</h2><p className="subtext">The call was {r.toss?.call}. {r.toss?.winner===r.you?"Set the tone for the match.":"Waiting for their decision."}</p>{r.toss?.winner===r.you?<div className="two-buttons"><button className="primary-button" disabled={busy} onClick={()=>act({action:"choose",choice:"bat"})}><Target size={19}/> Bat first</button><button className="secondary-button" disabled={busy} onClick={()=>act({action:"choose",choice:"bowl"})}><Zap size={19}/> Bowl first</button></div>:<p className="waiting-line"><LoaderCircle className="spin" size={18}/>Choosing to bat or bowl…</p>}</div>}
 {r.phase==="playing"&&(r.mode!==null?chooseCards():<div className="mode-panel"><span className="tag">A NEW BALL. A NEW PLAN.</span><h2>{isBatting?"Read the bowler.":"Pace or spin?"}</h2><p className="subtext">{isBatting?other?.name+" is choosing a bowling style. Your six shots are ready below.":"Choose your style before this ball. Then pick a delivery."}</p>{isBatting?<><div className="preview-shots">{shots.map((s,i)=><div key={s.name}><span>0{i+1}</span>{s.name}</div>)}</div><p className="waiting-line"><LoaderCircle size={18} className="spin"/>Waiting for the bowling style</p></>:<><RadioGroup value={style??""} onValueChange={v=>setStyle(v as Mode)} className="style-options" aria-label="Bowling style">{(["pace","spin"] as Mode[]).map(m=><label key={m} className={"style-card "+(style===m?"selected":"")}><RadioGroupItem className="sr-only" value={m} aria-label={m==="pace"?"Pace bowling":"Spin bowling"}/>{m==="pace"?<Zap size={30}/>:<Wind size={30}/>}<b>{m==="pace"?"PACE":"SPIN"}</b><span>{m==="pace"?"Speed. Swing. Surprise.":"Turn. Flight. Deception."}</span></label>)}</RadioGroup><button className="primary-button" disabled={busy||!style} onClick={()=>runAction({action:"mode",mode:style})}>Lock bowling style</button><p className="form-hint center">Choose again before every ball.</p></>}</div>)}
 {(r.phase==="result"||r.phase==="complete")&&last&&<div className="result-panel"><div className={"result-number "+(last.outcome==="W"?"out":"")}>{last.outcome}</div><span className="panel-kicker">BALL {over(last.number)} · {last.mode.toUpperCase()}</span><h2>{r.phase==="complete"?winnerName:resultTitle}</h2><p className="subtext">{r.phase==="complete"?(r.winner===null?"Scores level. Rivalry intact.":r.winner===innings?.batter?"Won with "+(3-(innings?.wickets??0))+" wicket"+(innings?.wickets===2?"":"s")+" in hand.":"Won by "+((r.innings[0]?.runs??0)-(r.innings[1]?.runs??0))+" runs."):last.outcome==="W"?"The bowler wins this battle.":Number(last.outcome)>=4?"A boundary worth the risk.":"Every run counts."}</p><div className="reveal"><div><span>THE SHOT</span><b>{shots[last.shot].name}</b></div><span className="versus">VS</span><div><span>THE DELIVERY</span><b>{deliveries[last.mode][last.delivery].name}</b></div></div>
 {r.phase==="result"?<>{ended&&r.innings.length===1&&<div className="innings-break"><b>Innings complete.</b><span>{r.players[1-batter].name} needs {target} to win.</span></div>}<button className="primary-button" disabled={busy||r.ready[r.you]} onClick={()=>runAction({action:"next"})}>{r.ready[r.you]?<><Check size={18}/>Ready. Waiting for opponent…</>:ended?"Start the chase":"Next ball"}</button><p className="form-hint center">{r.ready[1-r.you]?"Your opponent is ready.":"Both players must be ready to continue."}</p></>:<><button className="primary-button" disabled={busy||r.votes[r.you]} onClick={()=>act({action:"rematch"})}><Trophy size={18}/>{r.votes[r.you]?"Rematch requested. Waiting…":"Play a rematch"}</button><button className="text-button end-button" onClick={exit}>Back to match lobby</button>{r.votes[1-r.you]&&!r.votes[r.you]&&<p className="form-hint center">Your opponent wants a rematch.</p>}</>}</div>}
 </section></div>
 {innings&&innings.balls.length>0&&<section className="match-log"><div className="section-label">BALL-BY-BALL<span>INNINGS {r.innings.length}</span></div><div className="log-list">{innings.balls.slice().reverse().map(ball=><div className="log-row" key={ball.number}><span>{over(ball.number)}</span><b className={"log-outcome "+(ball.outcome==="W"?"out":"")}>{ball.outcome}</b><span>{shots[ball.shot].name}</span><span className="log-vs">vs</span><span>{deliveries[ball.mode][ball.delivery].name}</span><small>{ball.mode}</small></div>)}</div></section>}
 <footer className="page-footer"><span>A LITTLE CRICKET. A LOT OF RIVALRY.</span><span>ROOM {r.code}</span></footer></main>;
}
function SwordsLabel(){return <span className="prematch-title">GAME<br/>ON.</span>;}
