"use client";
import { useEffect, useState } from "react";
import Match from "./match";
import { useMatch } from "./use-match";
import { shots,deliveries,matchup, type Mode } from "@/lib/game";
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from "@/components/ui/table";
import { Zap, Users, Globe2, ShieldCheck, CircleHelp, Plus, LogIn, Swords, Trophy, LockKeyhole } from "lucide-react";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
export default function Home() {
  const game = useMatch();
 const [rulesMode,setRulesMode]=useState<Mode>("pace");
 useEffect(()=>{const invite=new URLSearchParams(location.search).get("room");if(invite){setTab("join");setCode(invite.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6));}},[]);
 const [tab, setTab] = useState("create"), [name, setName] = useState(""), [code, setCode] = useState(""), [overs, setOvers] = useState("3"), [help, setHelp] = useState(false), [error, setError] = useState("");
  return <div className="site-shell">
    <header className="topbar"><a className="brand" href="/" aria-label="SIX & OUT home"><span className="brand-mark"><Zap size={23} fill="currentColor" /></span><span>SIX<span className="lime">&</span>OUT<span className="brand-dot">.</span></span></a><nav><span className="nav-active">Play</span><button onClick={() => setHelp(true)}>How to play <CircleHelp size={16} /></button></nav><span className="header-note"><Globe2 size={16} /> TWO PLAYERS. ONE RIVALRY.</span></header>
    {game.room ? <Match room={game.room} busy={game.busy} error={game.error} act={game.act} exit={game.exit} showRules={()=>setHelp(true)}/> : <main className="lobby-main"><div className="page-label"><span className="small-line"/>THE MULTIPLAYER CRICKET DUEL<span className="edition">01 / MATCH LOBBY</span></div>
      <div className="lobby-grid"><section className="stadium-panel"><img className="stadium-image" src="/stadium.png" alt="Cricket stadium illuminated by floodlights at night"/><div className="stadium-shade"/><div className="hero-copy"><span className="tag"><Swords size={15}/> HEAD-TO-HEAD CRICKET</span><h1>YOUR SHOT.<br/>THEIR MOVE.<br/><span>GAME ON.</span></h1><p>Six shots. Six deliveries.<br/>One friend to outsmart.</p></div><div className="stadium-footer"><span className="stadium-caption">UNDER THE LIGHTS<br/><b>EVERY BALL IS A BATTLE.</b></span><span className="stadium-number">06<span>CHOICES.<br/>ENDLESS MIND GAMES.</span></span></div></section>
      <section className="setup-panel"><div className="panel-kicker"><span className="tiny-lime"/> MATCH SETUP</div><h2>Meet at the crease.</h2><p className="subtext">Create a room or join your opponent.</p>
      <Tabs value={tab} onValueChange={v => {setTab(v);setError("");}}><TabsList className="setup-tabs"><TabsTrigger value="create"><Plus size={17}/> Create room</TabsTrigger><TabsTrigger value="join"><LogIn size={17}/> Join room</TabsTrigger></TabsList></Tabs>
      <form onSubmit={e=>{e.preventDefault();setError("");void game.open(tab as "create"|"join",name,Number(overs),code).catch(e=>setError(e.message));}}><label className="field-label" htmlFor="player-name">YOUR PLAYER NAME</label><div className="input-wrap"><Users size={18}/><input id="player-name" placeholder="e.g. Captain Cool" value={name} maxLength={20} required onChange={e=>setName(e.target.value)} autoComplete="nickname"/></div>
      {tab === "create" ? <><div className="field-label overs-label">OVERS PER INNINGS <span>1–6 OVERS</span></div><RadioGroup className="overs-grid" value={overs} onValueChange={setOvers} aria-label="Overs per innings">{[1,2,3,4,5,6].map(n=><label className={overs===String(n)?"over-choice selected":"over-choice"} key={n}><RadioGroupItem value={String(n)} className="sr-only" aria-label={n+" overs"}/><span>{n}</span></label>)}</RadioGroup><p className="form-hint">{Number(overs)*6} balls per innings. Three wickets. All to play for.</p></> : <><label className="field-label" htmlFor="room-code">ROOM CODE</label><div className="input-wrap code-input"><LockKeyhole size={18}/><input id="room-code" placeholder="ABC123" value={code} minLength={6} maxLength={6} required autoComplete="off" onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,""))}/></div><p className="form-hint">Ask your opponent for their six-character code.</p></>}
      {(error||game.error)&&<p className="error-text" role="alert">{error||game.error}</p>}<button className="primary-button" type="submit" disabled={game.busy}>{game.busy?"Opening room…":tab==="create"?<><Plus size={19}/> Create match room</>:<><LogIn size={19}/> Join match room</>}</button></form>
      <div className="setup-footnote"><ShieldCheck size={16}/><span>Private room · Just you and your opponent</span></div><div className="setup-divider"/><div className="match-facts"><div><Users size={17}/><span>2 players</span></div><div><Trophy size={17}/><span>2 innings</span></div><div><Zap size={17}/><span>Your tactics</span></div></div></section></div>
      <section className="flow-strip" aria-label="Match steps">{[["01","WIN THE TOSS","Heads or tails. Bat or bowl."],["02","PICK YOUR PLAY","Choose your shot or delivery."],["03","OWN THE MATCH","Outthink. Outscore. Celebrate."]].map(([n,t,d])=><div className="flow-step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</section>
      <footer className="page-footer"><span>A LITTLE CRICKET. A LOT OF RIVALRY.</span><button onClick={()=>setHelp(true)}>Learn the rules <CircleHelp size={14}/></button></footer>
    </main>}
    <Dialog open={help} onOpenChange={setHelp}><DialogContent className="rules-dialog large"><DialogTitle>Six choices. Your call.</DialogTitle><DialogDescription>Create a room and send the code to a friend. The toss winner chooses to bat or bowl.</DialogDescription><div className="rules-copy"><p><b>Every ball:</b> the bowler first chooses pace or spin, then picks one of six deliveries. The batter secretly picks one of six shots. Both choices stay hidden until they are locked.</p><p><b>Runs or a wicket:</b> the matchup decides the result. Play to each shot’s strengths and anticipate your opponent.</p><p><b>Two innings:</b> each player bats for the selected overs or until three wickets fall. Chase one more than the first innings score. Equal scores are a tie.</p><p className="legend">The table shows the exact result for each matchup. W = wicket. Numbers = runs. No random scoring.</p></div><Tabs value={rulesMode} onValueChange={v=>setRulesMode(v as Mode)} className="rules-tabs"><TabsList><TabsTrigger value="pace">Pace matchups</TabsTrigger><TabsTrigger value="spin">Spin matchups</TabsTrigger></TabsList></Tabs><div className="rules-table-wrap"><Table className="rules-table"><TableHeader><TableRow><TableHead>Shot / Delivery</TableHead>{deliveries[rulesMode].map(d=><TableHead key={d.name}>{d.name}</TableHead>)}</TableRow></TableHeader><TableBody>{shots.map((s,i)=><TableRow key={s.name}><TableCell>{s.name}</TableCell>{matchup[rulesMode][i].map((result,j)=><TableCell className={result==="W"?"outcome-w":""} key={j}>{result}</TableCell>)}</TableRow>)}</TableBody></Table></div></DialogContent></Dialog>
  </div>;
}